sil14\VitrineBundle\Entity\Article:

        type: entity
        table: Article
        id :
                id :
                        type: integer
                        generator: {strategy: AUTO}

        fields:

                name:
                        type: string
                        lenght: 100
                price:
                        type: decimal
                        scale: 2
                description:
                        type: text

                stock :
                        type: integer

        manyToOne:
                categorie:
                        targetEntity: Categorie
                        inversedBy: articles
                        joinColumn:
                                name: category_id
                                referenceColumnName: id

        oneToMany:
                ligneArticles:
                        targetEntity: Lignecommande
                        mappedBy: article


