sil14\VitrineBundle\Entity\Client:

        type: entity
        table: Client
        id :
                id :
                        type: integer
                        generator: {strategy: AUTO}

        fields:

                name:
                        type: string
                        lenght: 100
                mail:
                        type: string
                        lenght: 100
                adresse:
                        type: string
                        lenght: 100

                pseudo:
                        type: string
                        lenght: 100

                password:
                        type: string
                        lenght: 100