sil14\VitrineBundle\Entity\Commande:

        type: entity
        table: Commande
        id :
                id :
                        type: integer
                        generator: {strategy: AUTO}

        fields:
                date:
                        type: date

                etat:
                        type: boolean

                client:
                        type: integer

        oneToMany:
                ligneCommandes:
                        targetEntity: Lignecommande
                        mappedBy: commande